name: hydrationPlugin
version: '${project.version}'
main: wpojek555.hydrationplugin.HydrationPlugin
api-version: 1.16
commands:
  hydrationLevel:
    description: This command gets the amount of level for you
  hydration:
    description: Plugin command;